### ISSUE TITLE
Unique transitionNames are required 

### ISSUE THREAD

**Issue by devmichealmurray** [material-components/material-components-android-motion-codelab#10]
In Section 4 at this point in the CodeLab:

> Try re-running the app. Pressing back after opening an email will collapse the email back into the list. Nice! Let's keep improving the animation.

The app crashes with this IllegalArgumentException: 

>     java.lang.IllegalArgumentException: Unique transitionNames are required for all sharedElements
        at androidx.fragment.app.FragmentTransaction.addSharedElement(FragmentTransaction.java:595)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:212)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:58)
        at androidx.navigation.NavController.navigate(NavController.java:1049)
        at androidx.navigation.NavController.navigate(NavController.java:935)
        at androidx.navigation.NavController.navigate(NavController.java:1128)
        at com.materialstudies.reply.ui.home.HomeFragment.onEmailClicked(HomeFragment.kt:106)
        at com.materialstudies.reply.databinding.EmailItemLayoutBindingImpl._internalCallbackOnClick(EmailItemLayoutBindingImpl.java:208)
        at com.materialstudies.reply.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:7356)
        at android.view.View.performClickInternal(View.java:7322)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27804)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by Dannark** [comment]
I had the same problem in my own app first time I tried that, the problem was because I put the transitionName and click listener in two different elements views in XML, you have to make sure to give a different transitionName to the view you send in the argument when clicking, for example:

**The right way:**
```xml
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent">

        <androidx.cardview.widget.CardView
            android:layout_width="130dp"
            android:layout_height="match_parent"
            android:clickable="true"
            android:transitionName="@{@string/post_card_transition_name(post.id)}"
            android:onClick="@{(view) -> clickListener.onClick(view, post)}"
            ...
```
if you see, in this case, android:transitionName will return post_card_1, post_card_2 post_card_3 etc...

**The wrong way:**
```xml
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:onClick="@{(view) -> clickListener.onClick(view, post)}">

        <androidx.cardview.widget.CardView
            android:layout_width="130dp"
            android:layout_height="match_parent"
            android:clickable="true"
            android:transitionName="@{@string/post_card_transition_name(post.id)}"
            ...
```

In this case, you are sending constraintLayout as a view that has no transitionName to it

See if your problem seems like that, the transition effect is so awesome, I will definitely always use that from now on
