### ISSUE TITLE
Appcompat:1.3.0 causing crash

### ISSUE THREAD

**Issue by noyalj** [material-components/material-components-android-motion-codelab#12]
When updating to ` 'androidx.appcompat:appcompat:1.3.0'` the email item to detail screen transition crashes. One of my other app uses 1.3.0 and runs fine but when I add an extra layout or even a menu with more than two items the app crashes. In case of the codelab example app this only happens after updating to `appcompat:1.3.0`. Also the crash does not apply to every email to detail transition. 

`java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.get(ArrayList.java:437)
        at androidx.fragment.app.FragmentTransitionImpl.setNameOverridesReordered(FragmentTransitionImpl.java:183)
        at androidx.fragment.app.DefaultSpecialEffectsController.startTransitions(DefaultSpecialEffectsController.java:665)
        at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:114)
        at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:294)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

**Comment by noyalj** [comment]
Okay the crash is gone after downgrading `androidx.fragment:fragment-ktx` from `1.3.4` to `1.3.3`

**Comment by LiMingA666** [comment]
I still need to downgrade from to androidx.appcompat:appcompat:1.3.0  1.20 ,This crash is not going to happen

**Comment by LiMingA666** [comment]
Can this problem be adapted in the future? Rather than relying on the downgrade

**Comment by noyalj** [comment]
It was an issue with the `androidx.fragment:fragment-ktx` transition. The issue is solved on `1.3.5`
